minimumReleaseAgeExclude:
  - astro@6.4.8 || 7.0.7
  - "@astrojs/telemetry@3.3.3"

shellEmulator: true
trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar@4.0.3
  - semver@6.3.1

allowBuilds:
  esbuild: true
  sharp: true
